apiVersion: apps/v1
kind: Deployment
metadata:
  name: crd-conversion-webhook
  namespace: crd-conversion-webhook
  labels:
    name: crd-conversion-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      name: crd-conversion-webhook
  template:
    metadata:
      labels:
        name: crd-conversion-webhook
    spec:
      containers:
       - name: crd-conversion-webhook
         image: quay.io/madorn/openshift-crd-conversion-webhook:latest
         args:
           - -tls-cert-file=/etc/webhook/certs/tls.crt
           - -tls-private-key-file=/etc/webhook/certs/tls.key
         ports:
         - name: tls
           containerPort: 6443
         volumeMounts:
           - name: webhook-certs
             mountPath: /etc/webhook/certs
             readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: crd-conversion-webhook.crd-conversion-webhook.svc
