apiVersion: v1
kind: Service
metadata:
  name: crd-conversion-webhook
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: crd-conversion-webhook.crd-conversion-webhook.svc
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    name: crd-conversion-webhook
  type: ClusterIP
